title: HiGlassRM
email: jnf0219@naver.com 
description: "A project website for the WACV2026 paper: HiGlassRM: Learning to Remove High-prescription Glasses via Synthetic Dataset Generation" 
baseurl: "" 

# Build settings
markdown: kramdown